version: '3.9'
services:
  client:
    build: 
      context: "MovieDB/Client/wwwroot"
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - "api"
  api:
    build: 
      context: "MovieDB/Server"
    container_name: "${API_CONT_NAME}"
    ports:
      - "${API_PORT}:80"
    depends_on:
      - "db"
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: "${DB_CONT_NAME}"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrongP@ssword
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - movieData:/var/opt/mssql:rw
  shared:
    build:
      context: "MovieDB/Shared"
    container_name: "${SHARED_CONT_NAME}"
    ports:
      - "${SHARED_PORT}:80"
    depends_on:
      - "api"
volumes:
  movieData: