version: '3.9'
services:
  client:
    build: 
      context: "MovieDB/Client/wwwroot"
    container_name: "movie-web-container"
    ports:
      - "8090:80"
    depends_on:
      - "api"
  api:
    build: 
      context: "MovieDB/Server"
    container_name: "movie-api-container"
    ports:
      - "8091:80"
    depends_on:
      - "db"
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: "movie-db-container"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrongP@ssword
    ports:
      - "8092:1433"
  shared:
    build:
      context: "MovieDB/Shared"
    container_name: "movie-shared-container"
    ports:
      - "8093:80"
    depends_on:
      - "api"